# Generated by Django 6.0.2 on 2026-02-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('technologies', models.CharField(help_text='Comma-separated tech stack', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/%Y/%m/')),
                ('github_url', models.URLField(blank=True, help_text='Link to GitHub repository', null=True)),
                ('live_url', models.URLField(blank=True, help_text='Link to live demo', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Display as featured project')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower appears first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Resume', max_length=200)),
                ('file', models.FileField(upload_to='documents/resume/')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this resume is currently available for download')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('web', 'Web & Backend Development'), ('data', 'Data Science & Libraries'), ('tools', 'Tools & Development Environment'), ('design', 'Design & Graphics'), ('office', 'Office Productivity')], max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency level 0-100')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order'],
            },
        ),
    ]
