# Generated by Django 6.0.2 on 2026-02-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('profile_image', models.ImageField(blank=True, help_text='Profile picture for about page', null=True, upload_to='profile/')),
                ('about_content', models.TextField(help_text='About me section (supports HTML)')),
                ('education_content', models.TextField(help_text='Education & achievements section (supports HTML)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this about section is displayed on the website')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
